### ISSUE TITLE
A couple of problems trying to run/debug current

### ISSUE THREAD

**Issue by tlemmons** [StanDeMan/RaspberryDebugger#9]
Great job on picking this up and running with it.  I just got the latest and was trying to build and use.  Ran into these problems and thought you might tell me what is going weong.

1  Connection.cs line 449 keeps exceptioning with "More then one entry".  It looks like the webpage https://dotnetversionfeed.azurewebsites.net/versions has many of the items in it three times.  I changed my code to FirstOrDefault instead of SingleOrDefault and it seemed to work but wanted to check on if that was an issue otherwise.

2.  PackageHelper.ch line 111.  I get here with _cachedSdkCatalog valid but empty quite often.  I am not sure how but I had to add a check for empty to the check for null to force the catalog to load first time.

3. With both of those items changed, I get to Connection.cs line 97 and enter the Connect function but it never returns and locks up the system.  All the parameters look valid going in.  I guess I can pull LinusSshProxy code and debug deeper, but hoped you might know what is going on first.  

Thanks for all you do on this project.

**Comment by StanDeMan** [comment]
Moved the .NET scraping part for searching version to a web service.
